definitions:
  req.CreateDeploymentReqDto:
    properties:
      branch_name:
        type: string
      docker_file_path:
        type: string
      env:
        additionalProperties: true
        type: object
      repository_provider:
        enum:
        - github
        type: string
      repository_url:
        type: string
      root_dir:
        type: string
    required:
    - repository_provider
    - repository_url
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Health Check
      tags:
      - Index
  /deployments:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Deployment Index
      tags:
      - Deployments
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Deployment Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/req.CreateDeploymentReqDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create Deployment
      tags:
      - Deployments
  /deployments/:id:
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update Deployment
      tags:
      - Deployments
  /deployments/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Show Deployment
      tags:
      - Deployments
swagger: "2.0"
