definitions:
  api_response.Response:
    properties:
      code:
        description: This is Name
        type: integer
      data: {}
      errors:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
  req.CreateDeploymentReqDto:
    properties:
      branch_name:
        type: string
      docker_file_path:
        type: string
      env:
        additionalProperties:
          type: string
        type: object
      repository_url:
        type: string
      root_dir:
        type: string
      title:
        type: string
    required:
    - branch_name
    - repository_url
    - title
    type: object
  req.UpdateDeploymentReqDto:
    properties:
      branch_name:
        type: string
      docker_file_path:
        type: string
      root_dir:
        type: string
      title:
        type: string
    type: object
  res.DeploymentDetailsRes:
    properties:
      _id:
        type: string
      branch_name:
        type: string
      container_id:
        type: string
      created_at:
        type: string
      docker_file_path:
        type: string
      docker_image_tag:
        type: string
      domain_url:
        type: string
      env:
        additionalProperties:
          type: string
        type: object
      last_deployed_at:
        type: string
      latest_status:
        type: string
      repository_name:
        type: string
      repository_provider:
        type: string
      repository_url:
        type: string
      root_directory:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  res.DeploymentLatestStatusRes:
    properties:
      _id:
        type: string
      domain_url:
        type: string
      last_deployed_at:
        type: string
      latest_status:
        type: string
    type: object
  res.DeploymentRes:
    properties:
      _id:
        type: string
      branch_name:
        type: string
      created_at:
        type: string
      domain_url:
        type: string
      last_deployed_at:
        type: string
      latest_status:
        type: string
      repository_provider:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  res.EventRes:
    properties:
      created_at:
        type: string
      deployment_id:
        type: string
      event_log_file_url:
        type: string
      id:
        type: string
      reason:
        type: string
      status:
        type: string
      title:
        type: string
      triggered_by:
        type: string
      triggered_value:
        type: string
      type:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Health Check
      tags:
      - Index
  /api/v1/deployments:
    get:
      consumes:
      - application/json
      parameters:
      - description: Page
        in: query
        name: page
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/res.DeploymentRes'
                  type: array
              type: object
      summary: Deployment Index
      tags:
      - Deployments
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Deployment Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/req.CreateDeploymentReqDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.DeploymentRes'
              type: object
      summary: Create Deployment
      tags:
      - Deployments
  /api/v1/deployments/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.DeploymentDetailsRes'
              type: object
      summary: Show Deployment
      tags:
      - Deployments
    patch:
      consumes:
      - application/json
      parameters:
      - description: Update Deployment Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/req.UpdateDeploymentReqDto'
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.DeploymentDetailsRes'
              type: object
      summary: Update Deployment
      tags:
      - Deployments
  /api/v1/deployments/{id}/env:
    put:
      consumes:
      - application/json
      parameters:
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.DeploymentDetailsRes'
              type: object
      summary: Update Deployment Env
      tags:
      - Deployments
  /api/v1/deployments/{id}/events:
    get:
      consumes:
      - application/json
      parameters:
      - description: Page
        in: query
        name: page
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/res.EventRes'
                  type: array
              type: object
      summary: Deployment Events
      tags:
      - Deployments
  /api/v1/deployments/{id}/rebuild-and-redeploy:
    post:
      consumes:
      - application/json
      parameters:
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.DeploymentDetailsRes'
              type: object
      summary: Rebuild and Deploy Deployment
      tags:
      - Deployments
  /api/v1/deployments/{id}/restart:
    post:
      consumes:
      - application/json
      parameters:
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.DeploymentDetailsRes'
              type: object
      summary: Restart Deployment
      tags:
      - Deployments
  /api/v1/deployments/{id}/stop:
    post:
      consumes:
      - application/json
      parameters:
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.DeploymentDetailsRes'
              type: object
      summary: Stop Deployment
      tags:
      - Deployments
  /api/v1/deployments/check-deploying-cron:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  type: integer
              type: object
      summary: Check Deploying state Deployments
      tags:
      - Deployments
  /api/v1/deployments/check-stopped-cron:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  type: integer
              type: object
      summary: Check Stopped Deployments
      tags:
      - Deployments
  /api/v1/deployments/latest-status:
    get:
      consumes:
      - application/json
      parameters:
      - description: Deployment ID
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api_response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/res.DeploymentLatestStatusRes'
                  type: array
              type: object
      summary: Deployments Latest Status
      tags:
      - Deployments
  /api/v1/repositories:
    get:
      consumes:
      - application/json
      parameters:
      - description: Repo Url
        in: query
        name: repo_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Repo Details
      tags:
      - Repositories
  /api/v1/repositories/branches:
    get:
      consumes:
      - application/json
      parameters:
      - description: Repo Url
        in: query
        name: repo_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Repo Branches
      tags:
      - Repositories
swagger: "2.0"
