definitions:
  req.CreateDeploymentReqDto:
    properties:
      branch_name:
        type: string
      docker_file_path:
        type: string
      env:
        additionalProperties:
          type: string
        type: object
      repository_url:
        type: string
      root_dir:
        type: string
      title:
        type: string
    required:
    - branch_name
    - repository_url
    - title
    type: object
  req.UpdateDeploymentReqDto:
    properties:
      branch_name:
        type: string
      docker_file_path:
        type: string
      root_dir:
        type: string
      title:
        type: string
    required:
    - branch_name
    - title
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Health Check
      tags:
      - Index
  /deployments:
    get:
      consumes:
      - application/json
      parameters:
      - description: Page
        in: query
        name: page
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Deployment Index
      tags:
      - Deployments
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Deployment Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/req.CreateDeploymentReqDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create Deployment
      tags:
      - Deployments
  /deployments/:id/env:
    put:
      consumes:
      - application/json
      parameters:
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update Deployment Env
      tags:
      - Deployments
  /deployments/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Show Deployment
      tags:
      - Deployments
    put:
      consumes:
      - application/json
      parameters:
      - description: Update Deployment Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/req.UpdateDeploymentReqDto'
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update Deployment
      tags:
      - Deployments
  /repositories:
    get:
      consumes:
      - application/json
      parameters:
      - description: Repo Url
        in: query
        name: repo_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Repo Details
      tags:
      - Repositories
swagger: "2.0"
