version: '3.9'

services:
  just-deploy:
    build: .
    restart: always
    hostname: just-deploy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test.rule=Host(`just-deploy-api.toufiq.dev`)"
    env_file:
      - .env
    volumes:
      - ./repos:$REPOSITORIES_PATH
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
networks:
  web:
    external: true