version: '3.9'

services:
  just-deploy:
    build: .
    restart: always
    hostname: just-deploy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deploy.rule=Host(`api.deploybl.com`)"
    env_file:
      - .env
    volumes:
      - ./repos:$REPOSITORIES_PATH
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    networks:
      - web
networks:
  web:
    external: true