// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/deployment_service.go
//
// Generated by this command:
//
//	mockgen -source=../../service/deployment_service.go --destination=./deployment_service_mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	models "github.com/toufiq-austcse/deployit/internal/api/deployments/model"
	api_response "github.com/toufiq-austcse/deployit/pkg/api_response"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockIDeploymentService is a mock of IDeploymentService interface.
type MockIDeploymentService struct {
	ctrl     *gomock.Controller
	recorder *MockIDeploymentServiceMockRecorder
	isgomock struct{}
}

// MockIDeploymentServiceMockRecorder is the mock recorder for MockIDeploymentService.
type MockIDeploymentServiceMockRecorder struct {
	mock *MockIDeploymentService
}

// NewMockIDeploymentService creates a new mock instance.
func NewMockIDeploymentService(ctrl *gomock.Controller) *MockIDeploymentService {
	mock := &MockIDeploymentService{ctrl: ctrl}
	mock.recorder = &MockIDeploymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeploymentService) EXPECT() *MockIDeploymentServiceMockRecorder {
	return m.recorder
}

// CountDeploymentByRepositoryName mocks base method.
func (m *MockIDeploymentService) CountDeploymentByRepositoryName(repositoryName string, ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDeploymentByRepositoryName", repositoryName, ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDeploymentByRepositoryName indicates an expected call of CountDeploymentByRepositoryName.
func (mr *MockIDeploymentServiceMockRecorder) CountDeploymentByRepositoryName(repositoryName, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDeploymentByRepositoryName", reflect.TypeOf((*MockIDeploymentService)(nil).CountDeploymentByRepositoryName), repositoryName, ctx)
}

// Create mocks base method.
func (m *MockIDeploymentService) Create(model *models.Deployment, ctx context.Context) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", model, ctx)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIDeploymentServiceMockRecorder) Create(model, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIDeploymentService)(nil).Create), model, ctx)
}

// FindByDeploymentStatus mocks base method.
func (m *MockIDeploymentService) FindByDeploymentStatus(status string) []models.Deployment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDeploymentStatus", status)
	ret0, _ := ret[0].([]models.Deployment)
	return ret0
}

// FindByDeploymentStatus indicates an expected call of FindByDeploymentStatus.
func (mr *MockIDeploymentServiceMockRecorder) FindByDeploymentStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDeploymentStatus", reflect.TypeOf((*MockIDeploymentService)(nil).FindByDeploymentStatus), status)
}

// FindById mocks base method.
func (m *MockIDeploymentService) FindById(id string, ctx context.Context) *models.Deployment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", id, ctx)
	ret0, _ := ret[0].(*models.Deployment)
	return ret0
}

// FindById indicates an expected call of FindById.
func (mr *MockIDeploymentServiceMockRecorder) FindById(id, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockIDeploymentService)(nil).FindById), id, ctx)
}

// FindBySubDomainName mocks base method.
func (m *MockIDeploymentService) FindBySubDomainName(domainName *string, ctx context.Context) *models.Deployment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySubDomainName", domainName, ctx)
	ret0, _ := ret[0].(*models.Deployment)
	return ret0
}

// FindBySubDomainName indicates an expected call of FindBySubDomainName.
func (mr *MockIDeploymentServiceMockRecorder) FindBySubDomainName(domainName, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySubDomainName", reflect.TypeOf((*MockIDeploymentService)(nil).FindBySubDomainName), domainName, ctx)
}

// FindUserDeploymentById mocks base method.
func (m *MockIDeploymentService) FindUserDeploymentById(id string, userId primitive.ObjectID, ctx context.Context) *models.Deployment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserDeploymentById", id, userId, ctx)
	ret0, _ := ret[0].(*models.Deployment)
	return ret0
}

// FindUserDeploymentById indicates an expected call of FindUserDeploymentById.
func (mr *MockIDeploymentServiceMockRecorder) FindUserDeploymentById(id, userId, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserDeploymentById", reflect.TypeOf((*MockIDeploymentService)(nil).FindUserDeploymentById), id, userId, ctx)
}

// GetContainerIdsFromDeployments mocks base method.
func (m *MockIDeploymentService) GetContainerIdsFromDeployments(deployments []models.Deployment) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerIdsFromDeployments", deployments)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetContainerIdsFromDeployments indicates an expected call of GetContainerIdsFromDeployments.
func (mr *MockIDeploymentServiceMockRecorder) GetContainerIdsFromDeployments(deployments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerIdsFromDeployments", reflect.TypeOf((*MockIDeploymentService)(nil).GetContainerIdsFromDeployments), deployments)
}

// GetDeploymentsByIds mocks base method.
func (m *MockIDeploymentService) GetDeploymentsByIds(ids []primitive.ObjectID, status string, ctx context.Context) ([]models.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentsByIds", ids, status, ctx)
	ret0, _ := ret[0].([]models.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentsByIds indicates an expected call of GetDeploymentsByIds.
func (mr *MockIDeploymentServiceMockRecorder) GetDeploymentsByIds(ids, status, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentsByIds", reflect.TypeOf((*MockIDeploymentService)(nil).GetDeploymentsByIds), ids, status, ctx)
}

// GetLatestStatusByIds mocks base method.
func (m *MockIDeploymentService) GetLatestStatusByIds(ids []string, userId primitive.ObjectID, ctx context.Context) ([]*models.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestStatusByIds", ids, userId, ctx)
	ret0, _ := ret[0].([]*models.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestStatusByIds indicates an expected call of GetLatestStatusByIds.
func (mr *MockIDeploymentServiceMockRecorder) GetLatestStatusByIds(ids, userId, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestStatusByIds", reflect.TypeOf((*MockIDeploymentService)(nil).GetLatestStatusByIds), ids, userId, ctx)
}

// IsRebuildAble mocks base method.
func (m *MockIDeploymentService) IsRebuildAble(deployment *models.Deployment) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRebuildAble", deployment)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRebuildAble indicates an expected call of IsRebuildAble.
func (mr *MockIDeploymentServiceMockRecorder) IsRebuildAble(deployment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRebuildAble", reflect.TypeOf((*MockIDeploymentService)(nil).IsRebuildAble), deployment)
}

// IsRestartable mocks base method.
func (m *MockIDeploymentService) IsRestartable(deployment *models.Deployment) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRestartable", deployment)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRestartable indicates an expected call of IsRestartable.
func (mr *MockIDeploymentServiceMockRecorder) IsRestartable(deployment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRestartable", reflect.TypeOf((*MockIDeploymentService)(nil).IsRestartable), deployment)
}

// IsStopAble mocks base method.
func (m *MockIDeploymentService) IsStopAble(deployment *models.Deployment) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStopAble", deployment)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStopAble indicates an expected call of IsStopAble.
func (mr *MockIDeploymentServiceMockRecorder) IsStopAble(deployment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStopAble", reflect.TypeOf((*MockIDeploymentService)(nil).IsStopAble), deployment)
}

// ListDeployment mocks base method.
func (m *MockIDeploymentService) ListDeployment(page, limit int64, userId primitive.ObjectID, ctx context.Context) ([]*models.Deployment, *api_response.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeployment", page, limit, userId, ctx)
	ret0, _ := ret[0].([]*models.Deployment)
	ret1, _ := ret[1].(*api_response.Pagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDeployment indicates an expected call of ListDeployment.
func (mr *MockIDeploymentServiceMockRecorder) ListDeployment(page, limit, userId, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeployment", reflect.TypeOf((*MockIDeploymentService)(nil).ListDeployment), page, limit, userId, ctx)
}

// UpdateDeployment mocks base method.
func (m *MockIDeploymentService) UpdateDeployment(deploymentId string, updates map[string]any, existingEvent *models.Event, ctx context.Context) (*models.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeployment", deploymentId, updates, existingEvent, ctx)
	ret0, _ := ret[0].(*models.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeployment indicates an expected call of UpdateDeployment.
func (mr *MockIDeploymentServiceMockRecorder) UpdateDeployment(deploymentId, updates, existingEvent, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeployment", reflect.TypeOf((*MockIDeploymentService)(nil).UpdateDeployment), deploymentId, updates, existingEvent, ctx)
}

// UpdateDeploymentStatusByContainerIds mocks base method.
func (m *MockIDeploymentService) UpdateDeploymentStatusByContainerIds(skipContainerIds []string, currentStatus, updatedStatus string, ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeploymentStatusByContainerIds", skipContainerIds, currentStatus, updatedStatus, ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeploymentStatusByContainerIds indicates an expected call of UpdateDeploymentStatusByContainerIds.
func (mr *MockIDeploymentServiceMockRecorder) UpdateDeploymentStatusByContainerIds(skipContainerIds, currentStatus, updatedStatus, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeploymentStatusByContainerIds", reflect.TypeOf((*MockIDeploymentService)(nil).UpdateDeploymentStatusByContainerIds), skipContainerIds, currentStatus, updatedStatus, ctx)
}

// UpdateLatestStatus mocks base method.
func (m *MockIDeploymentService) UpdateLatestStatus(deploymentId, status string, existingEvent *models.Event, context context.Context) (*models.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLatestStatus", deploymentId, status, existingEvent, context)
	ret0, _ := ret[0].(*models.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLatestStatus indicates an expected call of UpdateLatestStatus.
func (mr *MockIDeploymentServiceMockRecorder) UpdateLatestStatus(deploymentId, status, existingEvent, context any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLatestStatus", reflect.TypeOf((*MockIDeploymentService)(nil).UpdateLatestStatus), deploymentId, status, existingEvent, context)
}
