name: Build and publish deploybl server docker image
on:
  push:
    branches:
      - master
    paths:
      - web/**
jobs:
  setup-build-publish:
    name: Setup, Build, and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: server build and push to registry
        uses: docker/build-push-action@v3
        with:
          context: ./web/
          file: ./web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/deploybl-web:latest
